### ISSUE TITLE
关于其他字典检索问题

### ISSUE THREAD

**Issue by EmeryChan** [CNMan/HYDZD#3]
其他的字典如陆谷孙先生的《英汉大字典》是否也可以这样做呢？

**Comment by CNMan** [comment]
可以自己制作，不过路漫漫啊。。。
《汉语大字典》第2版字头检索表经`多人`、`多年`修订，才有如今的模样
我只是在前人基础上继续修订而已，工作量和他们不可同日而语

**Comment by EmeryChan** [comment]
谢谢告知






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CNMan"<notifications@github.com&gt;; 
发送时间: 2019年12月22日(星期天) 上午10:04
收件人: "CNMan/HYDZD"<HYDZD@noreply.github.com&gt;; 
抄送: "贝加庞克"<cy481367454@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CNMan/HYDZD] 关于其他字典检索问题 (#3)




可以自己制作，不过路漫漫啊。。。
 《汉语大字典》第2版字头检索表经多人、多年修订，才有如今的模样
 我只是在前人基础上继续修订而已，工作量和他们不可同日而语
